import { OpenApiGeneratorV3 } from "@asteasolutions/zod-to-openapi";
import { registry } from "../src/schemas.js";
import { writeFileSync } from "fs";

const generator = new OpenApiGeneratorV3(registry.definitions);

const document = generator.generateDocument({
  openapi: "3.0.0",
  info: {
    title: "Workflow Service",
    description: [
      "Workflow orchestration service. Create DAG workflows, modify them, and execute them by slug with runtime inputs.",
      "",
      "## Quick Start",
      "",
      "**Step 1 — Create a workflow:**",
      "```",
      "POST /workflows",
      '{ "featureSlug": "my-feature", "dag": { "nodes": [...], "edges": [...] } }',
      "```",
      "",
      "**Step 2 — Execute by slug (each time an event occurs):**",
      "```",
      "POST /workflows/by-slug/my-feature-obsidian/execute",
      '{ "inputs": { "email": "user@example.com" } }',
      "```",
      "Returns a run ID. Poll `GET /workflow-runs/{id}` for status and result.",
      "",
      "**Step 3 — Modify the workflow (metadata or DAG):**",
      "```",
      "PUT /workflows/{id}",
      '{ "dag": { "nodes": [...], "edges": [...] } }',
      "```",
      "If the DAG structure changed, a new workflow is created (fork). The response tells you what happened via `_action`.",
      "",
      "## DAG Format",
      "",
      "A DAG has `nodes` (steps) and `edges` (execution order).",
      "",
      "**Recommended node type: `http.call`** — calls any microservice by name:",
      "```json",
      '{',
      '  "id": "create-user",',
      '  "type": "http.call",',
      '  "config": { "service": "client", "method": "POST", "path": "/users" },',
      '  "inputMapping": { "body": "$ref:flow_input.userData" }',
      '}',
      "```",
      "The service name maps to env vars `{NAME}_SERVICE_URL` and `{NAME}_SERVICE_API_KEY`.",
      "To discover available services and their endpoints, use the API Registry.",
      "",
      "## Input Mapping ($ref syntax)",
      "",
      "Use `inputMapping` to pass data between nodes:",
      "- `$ref:flow_input.field` — from the workflow execution inputs",
      "- `$ref:node-id.output.field` — from a previous node's output",
      "",
      "## Features",
      "",
      "- Automatic retries (3 attempts, 5s apart) on each node",
      "- Async execution with status polling",
      "- Topological ordering — nodes run in dependency order",
      "- Native constructs: `wait` (delay), `condition` (branching), `for-each` (loops)",
      "",
      "## Per-App Secrets (BYOK)",
      "",
      "Some services (e.g. Stripe) require per-app API keys. **Never pass secrets as workflow inputs.**",
      "Instead, use the **key-service** app-keys system:",
      "",
      "**1. Register the key once (at app startup via `instrumentation.ts`):**",
      "```",
      "POST key-service /internal/app-keys",
      '{ "appId": "my-app", "provider": "stripe", "apiKey": "sk_live_xxx" }',
      "```",
      "",
      "**2. Pass `appId` (not the secret) in your workflow inputs:**",
      "```",
      "POST /workflows/by-name/create-course/execute",
      '{ "appId": "my-app", "inputs": { "courseName": "My Course", "price": 99 } }',
      "```",
      "",
      "**3. The downstream service resolves the key itself:**",
      "The service (e.g. stripe-service) receives `appId`, calls key-service",
      "`GET /internal/app-keys/stripe/decrypt?appId=my-app` to get the decrypted key.",
      "No secret ever transits through the workflow.",
      "",
      "## Setup Pattern (Next.js `instrumentation.ts`)",
      "",
      "Put all one-time setup in your app's `instrumentation.ts`:",
      "```typescript",
      "export async function register() {",
      "  // Register per-app secrets",
      "  await fetch(`${KEY_SERVICE_URL}/internal/app-keys`, {",
      '    method: "POST",',
      '    headers: { "Content-Type": "application/json", "x-api-key": KEY_SERVICE_API_KEY },',
      '    body: JSON.stringify({ appId: "my-app", provider: "stripe", apiKey: STRIPE_SECRET_KEY }),',
      "  });",
      "  // Create or update workflows via POST /workflows or PUT /workflows/{id}",
      "}",
      "```",
    ].join("\n"),
    version: "1.0.0",
  },
  servers: [
    {
      url: process.env.SERVICE_URL ?? "https://windmill.distribute.org",
    },
  ],
});

writeFileSync("openapi.json", JSON.stringify(document, null, 2));
console.log("Generated openapi.json");
